add description, authors and other info to project
JohanCodeForFun/quiz-app-for-teachers pull request #62
Opened 2023-03-27 19:57 UTC by JohanCodeForFun

2023-03-29 07:59 UTC, ElisNz requested changes

2023-03-29 07:59 UTC, ElisNz commented on DAAJE/package.json
> +  "author": "Daniel Naseri, Damir Dervovic, Elis Nilsen, Johan Hellberg",
Vi kanske bör lägga till våra nya medlemmar innan merge?

2023-03-30 08:46 UTC, JohanCodeForFun commented on DAAJE/package.json
> +  "author": "Daniel Naseri, Damir Dervovic, Elis Nilsen, Johan Hellberg",
Bra Ide Elis! La till Christopher Rönnberg. Axel hade just nu inte den tid och fokus han ville för det här projektet.

2023-03-30 10:49 UTC, ElisNz approved these changes

2023-03-30 10:49 UTC, merged